```{r, setup}
install.packages("dataRetrieval")
library(dataRetrieval)
```

```{r}
siteNumber <- "09379500"
ChoptankInfo <- readNWISsite(siteNumber)
parameterCd <- "00060"

# Raw daily data:
sanjuan_quantity_df <- readNWISdv(
  siteNumber, parameterCd,
  "2019-04-24", "2024-04-22"
)

pCode <- readNWISpCode(parameterCd)

```

```{r}
summary(sanjuan_quantity_df)
```

```{r}
siteNumber2<- "09380000"
ChoptankInfo2 <- readNWISsite(siteNumber2)
parameterCd2 <- "00065"

# Raw daily data:
colorado_quantity_df <- readNWISdv(
  siteNumber2, parameterCd2,
  "2019-04-24", "2024-04-22"
)

pCode2 <- readNWISpCode(parameterCd2)
```

```{r}
summary(colorado_quantity_df)
```
```{r setup, include=FALSE}
# Set your working directory

# Load your packages

# Set your ggplot theme

# Load your datasets

```


# Rationale and Research Questions



\newpage

# Dataset Information



\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 