---
title: "Water Quality"
author: "Siyu Dong & Samantha White"
date: "2024-04-26"
output: pdf_document
---
```{r setup, include=FALSE}
# Set your working directory
getwd()

# Load your packages
library(here)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(lubridate)

# Load your datasets
Boron_Site1 <- read.csv("./Raw_data/Boron_S1.csv", stringsAsFactors = TRUE)
Boron_Site2 <- read.csv("./Raw_data/Boron_S2.csv", stringsAsFactors = TRUE)
Magnesium_Site1 <- read.csv("./Raw_data/magnesium_S1.csv", stringsAsFactors = TRUE)
Magnesium_Site2 <- read.csv("./Raw_data/magnesium_S2.csv", stringsAsFactors = TRUE)
Uranium_Site1 <- read.csv("./Raw_data/Uranium_S1.csv", stringsAsFactors = TRUE)
Uranium_Site2 <- read.csv("./Raw_data/Uranium_S2.csv", stringsAsFactors = TRUE)
```

```{r, Dara Preparation}
#Chage Date Format
class(Boron_Site1$Activity_StartDate)
class(Boron_Site2$Activity_StartDate)
class(Magnesium_Site1$Activity_StartDate)
class(Magnesium_Site2$Activity_StartDate)
class(Uranium_Site1$Activity_StartDate)
class(Uranium_Sitew$Activity_StartDate)

Boron_Site1$Activity_StartDate <- as.Date(Boron_Site1$Activity_StartDate, format = "%Y-%M-%d")
Boron_Site2$Activity_StartDate <- as.Date(Boron_Site2$Activity_StartDate, format = "%Y-%M-%d")
Magnesium_Site1$Activity_StartDate <- as.Date(Magnesium_Site1$Activity_StartDate, format = "%Y-%M-%d")
Magnesium_Site2$Activity_StartDate <- as.Date(Magnesium_Site2$Activity_StartDate, format = "%Y-%M-%d")
Uranium_Site1$Activity_StartDate <- as.Date(Uranium_Site1$Activity_StartDate, format = "%Y-%M-%d")
Uranium_Site2$Activity_StartDate <- as.Date(Uranium_Site2$Activity_StartDate, format = "%Y-%M-%d")

class(Boron_Site1$Activity_StartDate)
class(Boron_Site2$Activity_StartDate)
class(Magnesium_Site1$Activity_StartDate)
class(Magnesium_Site2$Activity_StartDate)
class(Uranium_Site1$Activity_StartDate)
class(Uranium_Site2$Activity_StartDate)

#Merger Datasets respectivelly
Boron_merged <- bind_rows(Boron_Site1, Boron_Site2)
Magnesium_merged <- bind_rows(Magnesium_Site1, Magnesium_Site2)
Uranium_merged <- bind_rows(Uranium_Site1, Uranium_Site2)

#Unify the research time range
Uranium_filtered <- Uranium_merged %>%
  filter(Activity_StartDate >= as.Date("2018-01-01") & 
         Activity_StartDate <= as.Date("2023-12-31"))

#Generate the annual average concentration of three contaminations for both sites
Boron_merged$Year <- lubridate::year(Boron_merged$Activity_StartDate)
Boron_annual_average <- Boron_merged %>%
  group_by(Year, Location_Name) %>%
  summarise(Avg_Concentration = mean(Result_MeasureValue, na.rm = TRUE))

Magnesium_merged$Year <- lubridate::year(Magnesium_merged$Activity_StartDate)
Magnesium_annual_average <- Magnesium_merged %>%
  group_by(Year, Location_Name) %>%
  summarise(Avg_Concentration = mean(Result_MeasureValue, na.rm = TRUE))

Uranium_filtered$Year <- lubridate::year(Uranium_filtered$Activity_StartDate)
Uranium_annual_average <- Uranium_filtered %>%
  group_by(Year, Location_Name) %>%
  summarise(Avg_Concentration = mean(Result_MeasureValue, na.rm = TRUE))
```

```{r}
#Compare Boron
ggplot(Boron_annual_average, 
       aes(x = Year, y = Avg_Concentration, color = Location_Name)) +
  geom_point() +
  labs(title = "Boron Concentration before and after passing through the Navajo Nation",
       x = "Observation Year",
       y = "Mean Concentration (ug/L)")

#Compare Magnesium
ggplot(Magnesium_annual_average, 
       aes(x = Year, y = Avg_Concentration, color = Location_Name)) +
  geom_point() +
  labs(title = "Magnesium Concentration before and after passing through the Navajo Nation",
       x = "Observation Year",
       y = "Mean Concentration (ug/L)")

#Compare Uranium
ggplot(Uranium_annual_average, 
       aes(x = Year, y = Avg_Concentration, color = Location_Name)) +
  geom_point() +
  labs(title = "Uranium Concentration before and after passing through the Navajo Nation",
       x = "Observation Year",
       y = "Mean Concentration (ug/L)")
```

